package QL_DieuChuyen;

import DangNhap.DangNhap;
import MenuChuongTrinh.ThongTinNhom;
import QL_DanhSachTaiSan.DBEngine;
import QL_DanhSachTaiSan.JQLTaiSan;
import QL_DanhSachTaiSan.TaiSan;
import QL_MuaSam.JMSThietBi;
import QL_SuaChua.JQLSuaChua;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author vanqu
 */
public class JQLDieuChuyen extends javax.swing.JFrame {
    ArrayList<TaiSan> dsTaiSan = new ArrayList<>();
    ArrayList<TaiSan> dsTSWork = new ArrayList<>();
    ArrayList<TSDieuChuyen> dsDC = new ArrayList<>();
    ArrayList<TSDieuChuyen> dsDCWork = new ArrayList<>();
    int dongchon = -1;
    int chonts = -1;
    TaiSan tsan = new TaiSan();
    TSDieuChuyen dchuyen = new TSDieuChuyen();
    SimpleDateFormat format = new SimpleDateFormat("MM/dd/yyyy");
    DBEngine db = new DBEngine();
    String fDsTS = "dsTS.dat";
    String fDsDC = "dsDC.dat";
    /**
     * Creates new form JQLDieuChuyen
     */
    public JQLDieuChuyen() {
        initComponents();
        MyInit();
        jButtonChiTiet.setVisible(false);
        setLocationRelativeTo(null);
        setTitle("Quản lý điều chuyển tài sản");
    }
    public void MyInit(){
        //Khởi tạo dữ liệu khi chạy
        readData();
        LoadTableDC(dsDC);
        dsTSWork=dsTaiSan;
        dsDCWork = dsDC;
        LoadTableTSC(dsTSWork);        
        //Tạo combo danh mục để lọc
        String dm[]={"Tất cả","Nhà,công trình xây dựng","Vật kiến trúc","Xe ô tô","Máy móc, thiết bị","Cây, gia súc","Quyền tác giả",
                     "Quyền sở hữu công nghiệp","Quyền với giống cây trồng","Phần mềm ứng dụng","Khác"};
        jcboDMChon.setModel(new javax.swing.DefaultComboBoxModel(dm));
        jComboDCLoc.setModel(new javax.swing.DefaultComboBoxModel(dm));
    }
    public void LoadTableDC(ArrayList<TSDieuChuyen> ds){
        jTableDC.setModel(new TableTSDieuChuyen(ds));
    }
    public void LoadTableTSC(ArrayList<TaiSan> ds){
        jTableChonTS.setModel(new TableChonTS(ds));
    }
    public void readData(){
        try {
            dsTaiSan = (ArrayList<TaiSan>) db.docFile(fDsTS);
            dsDC = (ArrayList<TSDieuChuyen>) db.docFile(fDsDC);
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Có danh sách rỗng!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Lỗi đọc dữ liệu:\n" +ex,"Lỗi", JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(JQLTaiSan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void saveData(){        
        try {
            db.LuuFile(fDsDC,dsDC);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Lỗi lưu dữ liệu:\n" +ex,"Lỗi", JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(JQLTaiSan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDC = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jMaTS = new javax.swing.JTextField();
        jTenTS = new javax.swing.JTextField();
        jDvQL = new javax.swing.JTextField();
        jTinhTrang = new javax.swing.JTextField();
        jCBSD = new javax.swing.JTextField();
        jCBQL = new javax.swing.JTextField();
        jViTri = new javax.swing.JTextField();
        jNgaySD = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        labe2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jDM = new javax.swing.JTextField();
        jButtonThem = new javax.swing.JButton();
        jButtonHuy = new javax.swing.JButton();
        jButtonSua = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();
        jButtonThoat = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextDCToi = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableChonTS = new javax.swing.JTable();
        jcboDMChon = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboDCLoc = new javax.swing.JComboBox<>();
        jButtonChiTiet = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableDC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableDC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDCMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDC);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 1010, 220));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Thực hiện"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMaTS.setEditable(false);
        jMaTS.setToolTipText("Không thể sửa thông tin này");
        jPanel1.add(jMaTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 170, -1));

        jTenTS.setEditable(false);
        jTenTS.setToolTipText("Không thể sửa thông tin này");
        jPanel1.add(jTenTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 170, -1));

        jDvQL.setEditable(false);
        jDvQL.setToolTipText("Không thể sửa thông tin này");
        jPanel1.add(jDvQL, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 170, -1));

        jTinhTrang.setEditable(false);
        jTinhTrang.setToolTipText("Không thể sửa thông tin này");
        jPanel1.add(jTinhTrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 170, -1));
        jPanel1.add(jCBSD, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 170, -1));
        jPanel1.add(jCBQL, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 170, -1));

        jViTri.setToolTipText("");
        jPanel1.add(jViTri, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 170, -1));

        jNgaySD.setText("1/1/2000");
        jNgaySD.setToolTipText("Nhập định dạng ngày/tháng/năm");
        jPanel1.add(jNgaySD, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 170, -1));

        jLabel1.setText("Mã tài sản");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        labe2.setText("Tên tài sản");
        jPanel1.add(labe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel2.setText("Khoa quản lý");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel3.setText("Tình trạng");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel7.setText("CB sử dụng");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        jLabel6.setText("CB quản lý");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        jLabel5.setText("Vị trí đặt");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        jLabel4.setText("Ngày sử dụng");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        jLabel8.setText("Danh mục");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jDM.setEditable(false);
        jDM.setToolTipText("Không thể sửa thông tin này");
        jPanel1.add(jDM, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 170, -1));

        jButtonThem.setText("Thêm");
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 175, 70, -1));

        jButtonHuy.setText("Hủy");
        jButtonHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHuyActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 175, 70, -1));

        jButtonSua.setText("Sửa");
        jButtonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 175, 70, -1));

        jButtonXoa.setText("Xóa");
        jButtonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 175, 70, -1));

        jButtonThoat.setText("Thoát");
        jButtonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThoatActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 175, 70, -1));

        jLabel9.setText("Nơi điều chuyển");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));
        jPanel1.add(jTextDCToi, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 630, 210));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Chọn TS"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableChonTS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableChonTS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableChonTSMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableChonTS);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 350, 150));

        jcboDMChon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcboDMChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboDMChonActionPerformed(evt);
            }
        });
        jPanel2.add(jcboDMChon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 200, -1));

        jLabel10.setText("Lọc danh mục");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 23, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 370, 210));

        jComboDCLoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboDCLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboDCLocActionPerformed(evt);
            }
        });
        getContentPane().add(jComboDCLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 200, -1));

        jButtonChiTiet.setText("Xem chi tiết");
        jButtonChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChiTietActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonChiTiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 240, 170, -1));

        jMenu1.setText("Đăng xuất");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Thông tin");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Chức năng");

        jMenuItem1.setText("Mua sắm tài sản");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Danh sách tài sản");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Sửa chữa tài sản");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableChonTSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableChonTSMouseClicked
        // TODO add your handling code here:
        chonts = jTableChonTS.getSelectedRow();        
        if(chonts !=-1){
            tsan = dsTSWork.get(chonts);
            jDM.setText(tsan.getDanhMuc()+"");
            jMaTS.setText(tsan.getMaTS()+"");
            //jMaTS.setEnabled(false);
            jTenTS.setText(tsan.getTenTS()+"");
            jTinhTrang.setText(tsan.getTinhTrang()+"");
            jDvQL.setText(tsan.getKhoaQl()+"");            
        }
    }//GEN-LAST:event_jTableChonTSMouseClicked

    private void jTableDCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDCMouseClicked
        // TODO add your handling code here:
        dongchon = jTableDC.getSelectedRow();
        if(dongchon !=-1){
            dchuyen = dsDCWork.get(dongchon);
            jDM.setText(dchuyen.getTsX().getDanhMuc()+"");
            jMaTS.setText(dchuyen.getTsX().getMaTS()+"");
            //jMaTS.setEnabled(false);
            jTenTS.setText(dchuyen.getTsX().getTenTS()+"");
            jTinhTrang.setText(dchuyen.getTsX().getTinhTrang()+"");
            jDvQL.setText(dchuyen.getTsX().getKhoaQl()+"");
            jNgaySD.setText(dchuyen.getNgaySD()+"");
            jCBQL.setText(dchuyen.getCbQL()+"");
            jCBSD.setText(dchuyen.getCbSD()+"");
            jViTri.setText(dchuyen.getVtDat()+"");
            jTextDCToi.setText(dchuyen.getNoiDC()+"");
            jButtonChiTiet.setVisible(true);
            jButtonChiTiet.setText("Xem chi tiết: "+dchuyen.getTsX().getMaTS());
        }
    }//GEN-LAST:event_jTableDCMouseClicked

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        // TODO add your handling code here:
        //chonts = jTableChonTS.getSelectedRow();        
        if(chonts==-1)
            JOptionPane.showMessageDialog(null, "Hãy chọn tài sản để điều chuyển!\n","Thông báo", JOptionPane.WARNING_MESSAGE);
        else if(jTextDCToi.getText().trim().length() == 0 ||
                jCBQL.getText().trim().length() == 0)
            JOptionPane.showMessageDialog(null, "Nơi điều chuyển và cán bộ quản lý không được để trống!\n","Thông báo", JOptionPane.WARNING_MESSAGE);                    
        else{
            try {
                tsan = dsTSWork.get(chonts);
                dchuyen = new TSDieuChuyen(jTextDCToi.getText(),jCBQL.getText(),jCBSD.getText(),
                        jViTri.getText(),format.parse(jNgaySD.getText()),tsan);
                if(dsDC.contains(dchuyen))
                    JOptionPane.showMessageDialog(null, "Tài sản này đang được điều chuyển, hãy chọn tài sản khác!\n","Lỗi", JOptionPane.ERROR_MESSAGE);
                else{
                    dsDC.add(dchuyen);
                    LoadTableDC(dsDC);
                    saveData();
                    resetTxt();
                }
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "Hãy kiểm tra dữ liệu, định dạng ngày kiểu MM/dd/yyyy!\n" + ex,"Lỗi", JOptionPane.ERROR_MESSAGE);
//                Logger.getLogger(JQLDieuChuyen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jButtonThemActionPerformed

    private void jButtonHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHuyActionPerformed
        // TODO add your handling code here:
        resetTxt();
    }//GEN-LAST:event_jButtonHuyActionPerformed

    private void jcboDMChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboDMChonActionPerformed
        // TODO add your handling code here:
        ArrayList<TaiSan> dsLoc = new ArrayList<>();
        String itemLoc = jcboDMChon.getSelectedItem().toString();
        if(itemLoc.equalsIgnoreCase("Tất cả")){
            LoadTableTSC(dsTaiSan);
            dsTSWork=dsTaiSan;
        }            
        else{
            for(TaiSan itm : dsTaiSan) 
                if(itm.getDanhMuc().equalsIgnoreCase(itemLoc)) dsLoc.add(itm);
            LoadTableTSC(dsLoc);
            dsTSWork=dsLoc;
        }
    }//GEN-LAST:event_jcboDMChonActionPerformed

    private void jComboDCLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboDCLocActionPerformed
        // TODO add your handling code here:
        ArrayList<TSDieuChuyen> dcLoc = new ArrayList<>();
        String itemLoc = jComboDCLoc.getSelectedItem().toString();
        if(itemLoc.equalsIgnoreCase("Tất cả")){
            LoadTableDC(dsDC);
            dsDCWork = dsDC;
        }else{
            for(TSDieuChuyen itm : dsDC)
                if(itm.getTsX().getDanhMuc().equalsIgnoreCase(itemLoc)) dcLoc.add(itm);
            LoadTableDC(dcLoc);
            dsDCWork = dcLoc;
        }                
    }//GEN-LAST:event_jComboDCLocActionPerformed

    private void jButtonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaActionPerformed
        // TODO add your handling code here:
        dongchon = jTableDC.getSelectedRow();
        if(dongchon != -1){
            int response = JOptionPane.showConfirmDialog(null, "Bạn có muốn sửa không?", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION){
                try {
                    //dchuyen = dsDC.get(dongchon);
                    dchuyen = dsDCWork.get(dongchon);
                    dchuyen = dsDC.get(dsDC.indexOf(dchuyen));
                    dchuyen.setNoiDC(jTextDCToi.getText());
                    dchuyen.setCbQL(jCBQL.getText());
                    dchuyen.setCbSD(jCBSD.getText());
                    dchuyen.setVtDat(jViTri.getText());
                    dchuyen.setNgaySD(format.parse(jNgaySD.getText()));
                    LoadTableDC(dsDCWork);
                    resetTxt();
                    saveData();
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(null, "Hãy kiểm tra dữ liệu, định dạng ngày kiểu MM/dd/yyyy!\n" + ex,"Lỗi", JOptionPane.ERROR_MESSAGE);
                    //Logger.getLogger(JQLDieuChuyen.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        }else
            JOptionPane.showMessageDialog(null, "Cần chọn một bản ghi để sửa!", "Thông báo", JOptionPane.WARNING_MESSAGE);                
    }//GEN-LAST:event_jButtonSuaActionPerformed

    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaActionPerformed
        // TODO add your handling code here:
        dongchon = jTableDC.getSelectedRow();
        if (dongchon != -1){            
            dchuyen = dsDCWork.get(dongchon);            
            dchuyen = dsDC.get(dsDC.indexOf(dchuyen));
            int response = JOptionPane.showConfirmDialog(null, "Bạn có muốn xoá không?", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION){
                dsDC.remove(dchuyen);
                saveData();
                LoadTableDC(dsDC);
            }
        }else
            JOptionPane.showMessageDialog(null, "Cần chọn một bản ghi để xóa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButtonXoaActionPerformed

    private void jButtonChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChiTietActionPerformed
        // TODO add your handling code here:
        dongchon = jTableDC.getSelectedRow();
        dchuyen = dsDCWork.get(dongchon);
        dchuyen = dsDC.get(dsDC.indexOf(dchuyen));
        JXemChiTiet chiTietDC = new JXemChiTiet(dchuyen);
        chiTietDC.setVisible(true);
    }//GEN-LAST:event_jButtonChiTietActionPerformed

    private void jButtonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThoatActionPerformed
        // TODO add your handling code here:
        saveData();
        this.dispose();
    }//GEN-LAST:event_jButtonThoatActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JMSThietBi qlMSForm = new JMSThietBi();
        qlMSForm.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JQLTaiSan qlTSForm = new JQLTaiSan();
        qlTSForm.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        JQLSuaChua qlSCForm = new JQLSuaChua();
        qlSCForm.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        ThongTinNhom ttnForm = new ThongTinNhom();
        ttnForm.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        DangNhap dnForm = new DangNhap();
        dnForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked
    
    public void resetTxt(){
        jMaTS.setText("");
        jTenTS.setText("");
        jDvQL.setText("");
        jTinhTrang.setText("");
        jNgaySD.setText("01/01/2000");
        jDM.setText("");
        jCBQL.setText("");
        jCBSD.setText("");
        jTextDCToi.setText("");
        jViTri.setText("");
        jNgaySD.requestFocus();
//        chonts = -1;
        dongchon = -1;
        jButtonChiTiet.setVisible(false);
    }    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JQLDieuChuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JQLDieuChuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JQLDieuChuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JQLDieuChuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JQLDieuChuyen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChiTiet;
    private javax.swing.JButton jButtonHuy;
    private javax.swing.JButton jButtonSua;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonThoat;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JTextField jCBQL;
    private javax.swing.JTextField jCBSD;
    private javax.swing.JComboBox<String> jComboDCLoc;
    private javax.swing.JTextField jDM;
    private javax.swing.JTextField jDvQL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jMaTS;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JTextField jNgaySD;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableChonTS;
    private javax.swing.JTable jTableDC;
    private javax.swing.JTextField jTenTS;
    private javax.swing.JTextField jTextDCToi;
    private javax.swing.JTextField jTinhTrang;
    private javax.swing.JTextField jViTri;
    private javax.swing.JComboBox<String> jcboDMChon;
    private javax.swing.JLabel labe2;
    // End of variables declaration//GEN-END:variables
}
