/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QL_DieuChuyen;

/**
 *
 * @author vanqu
 */
public class JXemChiTiet extends javax.swing.JFrame {
    TSDieuChuyen dchuyen = new TSDieuChuyen();
    /**
     * Creates new form JXemChiTiet
     */
    public JXemChiTiet(){
        initComponents();
        setTitle("Chi tiết điều chuyển");
    }
    public JXemChiTiet(TSDieuChuyen tsdc) {
        initComponents();
        setTitle("Chi tiết điều chuyển");
        dchuyen = tsdc;
        setInfoDC();
        setInforTS();
    }
    private void setInforTS(){
        jLabelTen.setText(dchuyen.getTsX().getTenTS());
        jLabelMa.setText(dchuyen.getTsX().getMaTS());
        jLabelDV.setText(dchuyen.getTsX().getDvTinh());
        jLabelTTrang.setText(dchuyen.getTsX().getTinhTrang());
        jLabelDM.setText(dchuyen.getTsX().getDanhMuc());
        jLabelBaoHanh.setText(dchuyen.getTsX().getNgayBH());
        jLabelVon.setText(dchuyen.getTsX().getNguonVon());
        jLabelSoHuu.setText(dchuyen.getTsX().getSoHuu());
        jLabelMD.setText(dchuyen.getTsX().getMucDich());
        jLabelKhoa.setText(dchuyen.getTsX().getKhoaQl());
    }
    private void setInfoDC(){
        jLabelVTDC.setText(dchuyen.getNoiDC());
        jLabelNgay.setText(dchuyen.getNgaySD());
        jLabelCBQL.setText(dchuyen.getCbQL());
        jLabelCBSD.setText(dchuyen.getCbSD());
        jLabelVT.setText(dchuyen.getVtDat());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelMa = new javax.swing.JLabel();
        jLabelTen = new javax.swing.JLabel();
        jLabelDV = new javax.swing.JLabel();
        jLabelDM = new javax.swing.JLabel();
        jLabelTTrang = new javax.swing.JLabel();
        jLabelBaoHanh = new javax.swing.JLabel();
        jLabelVon = new javax.swing.JLabel();
        jLabelSoHuu = new javax.swing.JLabel();
        jLabelMD = new javax.swing.JLabel();
        jLabelTitl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelNgay = new javax.swing.JLabel();
        jLabelVT = new javax.swing.JLabel();
        jLabelCBQL = new javax.swing.JLabel();
        jLabelCBSD = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelKhoa = new javax.swing.JLabel();
        jLabelDCT = new javax.swing.JLabel();
        jLabelVTDC = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Chi tiết tài sản"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Mã tài sản:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Tên tài sản:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 90, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Đơn vị tính:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Danh mục:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Tình trạng:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 90, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Hạn bảo hành:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Nguồn vốn:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 90, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Sở hữu:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 90, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Mục đích dùng:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 90, -1));

        jLabelMa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelMa.setText("Mã");
        jPanel1.add(jLabelMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 190, -1));

        jLabelTen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTen.setText("Tên");
        jPanel1.add(jLabelTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 190, -1));

        jLabelDV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelDV.setText("DV");
        jPanel1.add(jLabelDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 190, -1));

        jLabelDM.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelDM.setText("DM");
        jPanel1.add(jLabelDM, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 190, -1));

        jLabelTTrang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTTrang.setText("Tinh trang");
        jPanel1.add(jLabelTTrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 190, -1));

        jLabelBaoHanh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelBaoHanh.setText("Bao hanh");
        jPanel1.add(jLabelBaoHanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 190, -1));

        jLabelVon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelVon.setText("Von");
        jPanel1.add(jLabelVon, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 190, -1));

        jLabelSoHuu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelSoHuu.setText("So huu");
        jPanel1.add(jLabelSoHuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 190, -1));

        jLabelMD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelMD.setText("Muc dich");
        jPanel1.add(jLabelMD, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 190, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 350, 220));

        jLabelTitl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitl.setText("CHI TIẾT ĐIỀU CHUYỂN TÀI SẢN");
        getContentPane().add(jLabelTitl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Thông tin điều chuyển")));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Vị trí đặt:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 90, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Ngày sử dụng:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 90, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("CB quản lý:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 90, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("CB sử dụng:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, -1));

        jLabelNgay.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelNgay.setText("Ngay");
        jPanel2.add(jLabelNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 190, -1));

        jLabelVT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelVT.setText("Vi tri");
        jPanel2.add(jLabelVT, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 190, -1));

        jLabelCBQL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCBQL.setText("CB quan");
        jPanel2.add(jLabelCBQL, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 190, -1));

        jLabelCBSD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCBSD.setText("CB dung");
        jPanel2.add(jLabelCBSD, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 190, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Khoa quản lý:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 90, -1));

        jLabelKhoa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelKhoa.setText("Khoa");
        jPanel2.add(jLabelKhoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 190, -1));

        jLabelDCT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelDCT.setText("Chuyển tới:");
        jPanel2.add(jLabelDCT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabelVTDC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelVTDC.setText("VT dieu chuyen");
        jPanel2.add(jLabelVTDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 190, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 350, 220));

        jButton1.setText("Xác nhận");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 100, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Dựa theo kế hoạch, đề nghị điều chuyển tài sản phiếu này thực hiện điều chuyển tài sản sau:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 530, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Người xét duyệt");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, -1, -1));

        jLabel17.setText("(Kí ghi rõ họ tên)");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JXemChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JXemChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JXemChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JXemChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JXemChiTiet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBaoHanh;
    private javax.swing.JLabel jLabelCBQL;
    private javax.swing.JLabel jLabelCBSD;
    private javax.swing.JLabel jLabelDCT;
    private javax.swing.JLabel jLabelDM;
    private javax.swing.JLabel jLabelDV;
    private javax.swing.JLabel jLabelKhoa;
    private javax.swing.JLabel jLabelMD;
    private javax.swing.JLabel jLabelMa;
    private javax.swing.JLabel jLabelNgay;
    private javax.swing.JLabel jLabelSoHuu;
    private javax.swing.JLabel jLabelTTrang;
    private javax.swing.JLabel jLabelTen;
    private javax.swing.JLabel jLabelTitl;
    private javax.swing.JLabel jLabelVT;
    private javax.swing.JLabel jLabelVTDC;
    private javax.swing.JLabel jLabelVon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
